### PR TITLE
To configure the Gateway in non-interactive mode

### PR DESCRIPTION
**Pull request by AlexeyALeonov**
It will make possible to configure the Gateway in non-interactive mode:
```
docker run -it --rm --mount type=bind,source=${PWD}/gateway,destination=/root/.local/share/storj/gateway/ --name gateway storjlabs/gateway:b8e4299-v1.1.0-go1.13.8 --non-interactive --server.address=":7777" --access 15....
```

### CODE REVIEW

**Comment by ifraixedes** [comment]
I believe that's more difficult to maintain and understand that the docker container behaves differently than the plain binary, so I would mostly remove the auto calling setup when there is no config file and just pass the `$@` directly to `gateway` so the user decides if running `setup`, `run` or whatsoever else.

**Comment by mniewrzal** [comment]
> I believe that's more difficult to maintain and understand that the docker container behaves differently than the plain binary, so I would mostly remove the auto calling setup when there is no config file and just pass the `$@` directly to `gateway` so the user decides if running `setup`, `run` or whatsoever else.

yeah, I started discussion if there are objections about removing forcing setup/run.

**Comment by mniewrzal** [comment]
I made change to remove setup from entrypoint completely https://review.dev.storj.io/c/storj/gateway/+/1811

**Comment by mniewrzal** [comment]
@AlexeyALeonov PR https://review.dev.storj.io/c/storj/gateway/+/1811 is merged, is it ok to close this change?

**Comment by AlexeyALeonov** [comment]
https://review.dev.storj.io/c/storj/gateway/+/1811 merged

**Pull request closed without merging**
