### PR TITLE
Update gateway.go

### PR DESCRIPTION
**Pull request by D4rk4**
Fix of https://github.com/storj/gateway/issues/8

### CODE REVIEW

**Comment by stefanbenten** [comment]
@D4rk4 This is not a fix for the issue. This restriction is intentional.

**Comment by D4rk4** [comment]
This restriction broking S3 capability. Probably it's affect not only S3QL... because you restrict list requeest like LIST blah_, only LIST blah/ allowed. It's realy very stupid design.

**Comment by egonelbre** [comment]
The reason for this restriction is that all the key components are encrypted and there's no easy way to create an encrypted prefix of a key component.

To illustrate:
```
hello/alpha/file.txt
hello/alpha-alpha/file.txt
hello/beta/file.txt
```

When we use prefix="hello/alpha" the non-recursive listing output should be:
```
hello/alpha/file.txt
hello/alpha-alpha/file.txt
```

However this does not work on encrypted paths, here's what an encrypted output could look like:
```
cRHFlKyl../Xy5TVr6.../FB6YYG...
cRHFlKyl.../i0XmNd.../wNSNrV...
cRHFlKyl.../c14YM9.../FuW0gx...
```

There's no way to construct an encrypted prefix that would match  both "alpha" and "alpha-alpha".

The alternatives would be to handle all the filtering on the client side. i.e. match upto `cRHFlKyl../` and then filter out using the decrypted prefixes. This of course would be really slow if that specific prefix contained millions of entries. Unfortunately, we haven't gotten to implementing this part yet.

This is the reason we require prefixes to have "/" at the end. We might lift this restriction, however it would still be slow due to encryption.

**Comment by stefanbenten** [comment]
@D4rk4 Any updates on this?

**Comment by stefanbenten** [comment]
Closing due to inactivity.

**Pull request closed without merging**
